### ISSUE TITLE
No module named 'image_warp'

### ISSUE THREAD

**Issue by qs956** [opnumten/M-TRACK#1]
When i run MTRACK_GUI.py in windows 10 with Python3.7.6 , I got this error:

Traceback (most recent call last):
  File "MTRACK_GUI.py", line 14, in <module>
    from traj_analysis import Traj_analysis
  File "D:\GitHub\M-TRACK\mtrack\traj_analysis.py", line 30, in <module>
    from traj_scale import sp_traj_scaling
  File "D:\GitHub\M-TRACK\mtrack\traj_scale.py", line 11, in <module>
    import image_warp
ModuleNotFoundError: No module named 'image_warp'

I have searched pypi.org but got nothing. I think may be i have missed something?

**Comment by FrickTobias** [comment]
It seems to me like image_warp is a reference to an in-house developed function. 

However, since there are no other references to this function in any of the files, I would suggest just removing the import line. If you try it and confirm it works we could suggest an edit to the package in a pull request.
